REL: 2021.2
qiime2/action-library-packaging pull request #13
Opened 2021-02-24 19:49 UTC by andrewsanchez

2021-02-24 20:47 UTC, thermokarst requested changes

2021-02-24 20:47 UTC, thermokarst commented on src/main.ts
> +      return 'qiime2/label/r2021.2'
The "staging" case just above this needs to be updated, too (to 2021.4) - thanks!

2021-02-24 23:02 UTC, thermokarst commented on src/main.ts
> +      return 'qiime2/label/r2021.2'
Great, thanks! Unfortunately you'll have to rerender the output, using `npm run all`.

2021-02-25 17:02 UTC, thermokarst commented on package.json
> +    "@types/node": "^14.14.31",
Where did this come from?

2021-03-01 16:57 UTC, thermokarst commented on package.json
> +    "@types/node": "^14.14.31",
Its not a problem, that its added, I just want to be sure I understand why it was added, before merging.

2021-03-01 22:30 UTC, andrewsanchez commented
@thermokarst, after a simple re-run of the workflow, it looks like the check passed without any mention of issues related to the change from lockfile version 1 to 2.  I'll go ahead and assign to you for review.

2021-03-01 23:08 UTC, thermokarst commented on package.json
> +    "@types/node": "^14.14.31",
For any folks just passing by, @andrewsanchez & I connected offline - sounds like he wrote his responses as a PR review, and didn't submit until after my second post. Interestingly enough, GH still maintains the insertion order of the comments, even though you'll see that the timestamps don't match up at all. TIL!

2021-03-01 23:53 UTC, andrewsanchez commented
I got a notification about this regarding a "mention," but I don't actually see any new activity here 🤔 .

2021-03-01 23:55 UTC, thermokarst commented
> I got a notification about this regarding a "mention," but I don't actually see any new activity here 🤔 .

https://github.com/qiime2/action-library-packaging/pull/13#discussion_r585116130

![Screen Shot 2021-03-01 at 4 54 46 PM](https://user-images.githubusercontent.com/274668/109575343-dae0dd00-7aae-11eb-8fb0-8cebf015c70b.png)

2021-03-01 23:58 UTC, andrewsanchez commented
Interesting.  I wonder if I accidentally resolved the conversation before seeing your coment.

2021-03-02 00:14 UTC, thermokarst commented
> I wonder if I accidentally resolved the conversation before seeing your coment.

It was already marked as "resolved" at the time that I wrote and submitted the comment.

2021-03-05 16:19 UTC, thermokarst approved these changes

2021-03-05 16:19 UTC, merged